mutation CreatePost($input: PostInput!) {
    createPost(input: $input) {
        id
        status
        post: result {
            title
            body
            publishedAt
        }
        author {
            name
            roles
        }
        errors {
            field
            message
        }
    }
}
