query GetFullWorkspace {
    workspace(id: "ws_123") {
        name
        slug
        owner: creator {
            id
            email
            thumbnail: avatarUrl
        }
        channels {
            id
            name
            topic
            lastMessage {
                content
                sentAt
                author {
                    username
                }
            }
        }
        settings {
            privacy {
                isPrivate
                discoveryLevel
            }
        }
    }
}
